# monolog:
#     handlers:
#         main:
#             type: stream
#             path: "%env(resolve:LOG_FILE)%"
#             level: debug
#         console:
#             type: console
#             process_psr_3_messages: false
#             level: debug


monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            level: debug
