nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000'] # L'URL de votre frontend React
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/': ~  # Appliquer les règles CORS à toutes les routes qui commencent par /api
