# nelmio_cors:
#     defaults:
#         allow_origin: ['http://localhost:3000','https://mon-portfolio-tawny-sigma.vercel.app']
#         allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: []
#         max_age: 3600
#     paths:
#         '^/api/':
#             allow_origin: ['http://localhost:3000','https://mon-portfolio-tawny-sigma.vercel.app']





nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
