# nelmio_cors:
#     defaults:
#         allow_credentials: true
#         allow_origin: ['http://localhost:3000'] # L'URL de votre frontend React
#         allow_headers: ['Content-Type', 'Authorization']
#         allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#         expose_headers: []
#         max_age: 3600
#     paths:
#         '^/api/': ~  # Appliquer les règles CORS à toutes les routes qui commencent par /api






# # config/packages/nelmio_cors.yaml
# nelmio_cors:
#     defaults:
#         allow_origin: ['http://localhost:3000'] # L'URL de votre frontend React
#         allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#         allow_headers: ['Content-Type', 'Authorization']
#         max_age: 3600
#         allow_credentials: true
#     paths:
#         '^/api/':
#             allow_origin: ['http://localhost:3000'] # L'URL de votre frontend React
#             allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#             allow_headers: ['Content-Type', 'Authorization']
#             max_age: 3600
#             allow_credentials: true












# # config/packages/nelmio_cors.yaml
# nelmio_cors:
#     defaults:
#         allow_origin: ['%env(FRONTEND_URL)%']
#         allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#         allow_headers: ['Content-Type', 'Authorization']
#         max_age: 3600
#         allow_credentials: true
#     paths:
#         '^/api/':
#             allow_origin: ['%env(FRONTEND_URL)%']
#             allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#             allow_headers: ['Content-Type', 'Authorization']
#             max_age: 3600
#             allow_credentials: true













# # config/packages/nelmio_cors.yaml
# nelmio_cors:
#     defaults:
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#         allow_headers: ['Content-Type', 'Authorization']
#         max_age: 3600
#         allow_credentials: true
#     paths:
#         '^/api/':
#             allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#             allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#             allow_headers: ['Content-Type', 'Authorization']
#             max_age: 3600
#             allow_credentials: true












# # config/packages/nelmio_cors.yaml
# nelmio_cors:
#     defaults:
#         allow_origin: ['http://localhost:3000', 'https://mon-portfolio-eta-ten.vercel.app']
#         allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#         allow_headers: ['Content-Type', 'Authorization']
#         max_age: 3600
#         allow_credentials: true
#     paths:
#         '^/api/':
#             allow_origin: ['http://localhost:3000', 'https://mon-portfolio-eta-ten.vercel.app']
#             allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#             allow_headers: ['Content-Type', 'Authorization']
#             max_age: 3600
#             allow_credentials: true












# nelmio_cors:
#     defaults:
#         allow_origin: '%env(array:FRONTEND_URLS)%'
#         allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#         allow_headers: ['Content-Type', 'Authorization']
#         max_age: 3600
#         allow_credentials: true
#     paths:
#         '^/api/':
#             allow_origin: '%env(array:FRONTEND_URLS)%'
#             allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#             allow_headers: ['Content-Type', 'Authorization']
#             max_age: 3600
#             allow_credentials: true








# nelmio_cors:
#     defaults:
#         allow_origin: '%env(array:CORS_ALLOW_ORIGIN)%'
#         allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#         allow_headers: ['Content-Type', 'Authorization']
#         max_age: 3600
#         allow_credentials: true
#     paths:
#         '^/api/':
#             allow_origin: '%env(array:CORS_ALLOW_ORIGIN)%'





nelmio_cors:
    defaults:
        allow_origin: ['https://mon-portfolio-tawny-sigma.vercel.app']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['https://mon-portfolio-tawny-sigma.vercel.app']
