# nelmio_cors:
#     defaults:
#         allow_origin: ['*']
#         allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#         allow_headers: ['Content-Type', 'Authorization']
#         max_age: 3600
#         allow_credentials: true
#     paths:
#         '^/api/':
#             allow_origin: ['*']











nelmio_cors:
    defaults:
        allow_origin: ['*']  # Autorise toutes les origines
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']  # Autorise toutes les méthodes HTTP nécessaires
        allow_headers: ['Content-Type', 'Authorization']  # Autorise les en-têtes requis
        allow_credentials: false  # Les cookies et les informations d'authentification ne sont pas partagés
        max_age: 3600  # Cache la configuration CORS dans les navigateurs
    paths:
        '^/api/':  # Applique cette règle aux routes sous /api/
            allow_origin: ['*']
