# config/services.yaml

parameters:
    # Vous pouvez définir des paramètres globaux ici, comme l'URL de la base de données, etc.
    # Ces paramètres ne changent pas d'un environnement à l'autre.
    # Exemple :
    # database_url: 'mysql://db_user:db_password@localhost:3306/db_name'

services:
    # Configuration par défaut pour tous les services dans ce fichier
    _defaults:
        autowire: true      # Symfony va injecter automatiquement les dépendances des services
        autoconfigure: true # Symfony va automatiquement enregistrer les services comme des événements, des abonnés, etc.

    # Définition des services basés sur les classes dans le répertoire src/
    # Cela permet à Symfony de connaître toutes les classes du répertoire `src/` et de les utiliser comme des services
    App\:
        resource: '../src/'  # Symfony va scanner tout le répertoire src/ pour y détecter les classes
        exclude:
            - '../src/DependencyInjection/' # On exclut certains répertoires (comme DependencyInjection) si nécessaire
            - '../src/Entity/' # On exclut les entités, elles ne sont pas des services
            - '../src/Kernel.php' # On exclut le fichier Kernel.php car ce n'est pas un service

    # Définition d'un service spécifique pour PageVisitRepository
    # Si vous avez un service qui n'est pas automatiquement configuré ou nécessite des arguments spécifiques :
    App\Repository\PageVisitRepository:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'  # Injection explicite de l'EntityManager
